export const events = [
  {
    id: 'dla vjti',
    name: 'LitFest by DLA VJTI',
    badge: 'College Event',
    date: 'January 2, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'dla vjti',
    name: 'LitFest by DLA VJTI',
    badge: 'College Event',
    date: 'January 3, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },

  {
    id: 'pratibimb vjti',
    name: 'Pratibimb',
    badge: 'College Event',
    date: 'January 4, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'pratibimb vjti',
    name: 'Pratibimb',
    badge: 'College Event',
    date: 'January 5, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'pratibimb vjti',
    name: 'Pratibimb',
    badge: 'College Event',
    date: 'January 6, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },

  {
    id: 'rangavardhan vjti',
    name: 'Rangavardhan',
    badge: 'College Event',
    date: 'January 7, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'rangavardhan vjti',
    name: 'Rangavardhan',
    badge: 'College Event',
    date: 'January 8, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'rangavardhan vjti',
    name: 'Rangavardhan',
    badge: 'College Event',
    date: 'January 9, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },

  {
    id: 'ecell vjti',
    name: 'Ecell',
    badge: 'College Event',
    date: 'January 10, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'ecell vjti',
    name: 'Ecell',
    badge: 'College Event',
    date: 'January 11, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },

  {
    id: 'technovanza vjti',
    name: 'Technovanza',
    badge: 'College Event',
    date: 'January 12, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'technovanza vjti',
    name: 'Technovanza',
    badge: 'College Event',
    date: 'January 13, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'technovanza vjti',
    name: 'Technovanza',
    badge: 'College Event',
    date: 'January 14, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },

  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 8, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 9, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 10, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 11, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 12, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 13, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 14, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 15, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 16, 2024',
    color: '#63d867',
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 17, 2024',
    color: '#63d867',
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 18, 2024',
    color: '#63d867',
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 19, 2024',
    color: '#63d867',
  },
  {
    id: 'enthusia vjti',
    name: 'Enthusia',
    badge: 'College Event',
    date: 'February 20, 2024',
    color: '#63d867',
  },

  {
    id: 'nexus vjti',
    name: 'Nexus by Digital VJTI',
    badge: 'College Event',
    date: 'February 24, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },
  {
    id: 'nexus vjti',
    name: 'Nexus by Digital VJTI',
    badge: 'College Event',
    date: 'February 25, 2024',
    color: '#63d867',
    type: 'event',
    everyYear: false,
  },

  {
    id: 'new year',
    name: 'New Year',
    badge: 'PublicHoliday',
    date: 'January 1, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
  {
    id: 'republic day',
    name: 'Republic Day',
    badge: 'PublicHoliday',
    date: 'January 26, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
  {
    id: 'holi',
    name: 'Holi',
    badge: 'PublicHoliday',
    date: 'March 10, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
  {
    id: 'good friday',
    name: 'Good Friday',
    badge: 'PublicHoliday',
    date: 'April 19, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
  {
    id: 'eid al fitr',
    name: 'Eid al Fitr',
    badge: 'PublicHoliday',
    date: 'April 29, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
  {
    id: 'independence day',
    name: 'Independence Day',
    badge: 'PublicHoliday',
    date: 'August 15, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
  {
    id: 'ganesh chaturthi',
    name: 'Ganesh Chaturthi',
    badge: 'PublicHoliday',
    date: 'September 2, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
  {
    id: 'diwali',
    name: 'Diwali',
    badge: 'PublicHoliday',
    date: 'October 24, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
  {
    id: 'eid al adha',
    name: 'Eid al-Adha',
    badge: 'PublicHoliday',
    date: 'October 30, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
  {
    id: 'guru nanak jayanti',
    name: 'Guru Nanak Jayanti',
    badge: 'PublicHoliday',
    date: 'November 12, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
  {
    id: 'christmas',
    name: 'Christmas',
    badge: 'PublicHoliday',
    date: 'December 25, 2024',
    type: 'holiday',
    color: '#63d867',
    everyYear: true,
  },
];
